version: '3.8'
services:
     youtube-stream:
       build: .
       image: decade27/youtube-livestream-docker:latest
       container_name: youtube_stream
       volumes:
         - ./audio:/app/audio
         - ./video:/app/video
       environment:
         - YOUTUBE_KEY=YOUR_YOUTUBE_STREAM_KEY  # Set your stream key as an environment variable
         - YOUTUBE_URL=YOUR_YOUTUBE_URL # Set your YouTube stream URL variable
       command: python /app/stream.py
       restart: unless-stopped